---
kind: secret
name: slack-webhook

get:
  path: drone-kubernetes-secrets-data
  name: slack-webhook
---
kind: pipeline
type: kubernetes
name: build-test

volumes:
  - name: deps
    temp: {}

clone:
  depth: 50

steps:
  - name: slack-notification-start-build-images
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack-webhook
      channel: ci
      username: drone
      template: >
        <{{ build.link }}|Container build(s) #{{ build.number }} started>
        <http://github.com/{{ repo.owner }}/{{ repo.name }}/tree/{{ build.branch }}|
        on {{ repo.name }}:{{ build.branch }}> by {{ build.author }}

  - name: build-modules
    image: us.gcr.io/para-devops/gotest:1.16.2
    volumes:
      - name: deps
        path: /go
    environment:
      GOPRIVATE: github.com/ParaServices/*
    commands:
      - go mod tidy
      - go build -v ./...

  - name: test
    image: us.gcr.io/para-devops/gotest:1.16.2
    volumes:
      - name: deps
        path: /go
    depends_on:
      - build-modules

  - name: slack-notification-finish-test
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack-webhook
      channel: ci
      username: drone
      template: >
        <{{ build.link }}|Build #{{ build.number }} {{ build.status }}>
        on <http://github.com/{{ repo.owner }}/{{ repo.name }}/tree/{{ build.branch }}|
        {{ repo.name }}:{{ build.branch }}> by @{{ build.author }}
    depends_on:
      - test
    when:
      status:
        - success
        - failure
